name: CI

on: [push]

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    container:
      image: ghcr.io/zen0x7f/container:debug

    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: service_password
          MYSQL_USER: user
          MYSQL_PASSWORD: service_password
          MYSQL_DATABASE: service
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory /__w/Service/Service
          git clone https://github.com/zen0x7f/service.git .
          git checkout ${{ github.sha }}

      - name: Prepare project
        run: |
          composer install
          yarn
          cp .env.ci .env
          php artisan key:generate

      - name: Prepare database
        env:
          DB_HOST: mysql
          DB_PORT: 3306
        run: |
          php artisan migrate
          php artisan db:seed

      - name: Prepare assets
        run: |
          yarn build

      - name: Run tests
        env:
          DB_HOST: mysql
          DB_PORT: 3306
        run: |
          # Running default tests
          php artisan test --coverage --coverage-clover storage/coverage/coverage.xml
          # Running PHP style test
          ./vendor/bin/pint --test

      - uses: codecov/codecov-action@v3
        if: ${{ matrix.platform == 'linux/amd64' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./storage/coverage/coverage.xml
